import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    const { name, email, phone, message } = await req.json();

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // --- ENHANCED PROFESSIONAL HTML TEMPLATE ---
    const htmlTemplate = `
      <div style="background-color: #f4f7f9; padding: 40px 10px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); border: 1px solid #e1e8ed;">
          
          <div style="background-color: #007bff; padding: 25px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 1px;">New Website Inquiry</h1>
          </div>

          <div style="padding: 30px;">
            <p style="font-size: 16px; color: #333; margin-bottom: 25px;">You have received a new message through your website contact form. Here are the details:</p>
            
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #666; width: 30%;"><strong>Full Name</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #333;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #666;"><strong>Email</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #007bff;">
                  <a href="mailto:${email}" style="text-decoration: none; color: #007bff;">${email}</a>
                </td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #666;"><strong>Phone</strong></td>
                <td style="padding: 10px 0; border-bottom: 1px solid #eee; color: #333;">${phone}</td>
              </tr>
            </table>

            <div style="margin-top: 30px; padding: 20px; background-color: #f8f9fa; border-radius: 6px; border: 1px dashed #ced4da;">
              <p style="margin-top: 0; color: #666; font-size: 14px; font-weight: bold; text-transform: uppercase;">Message Content:</p>
              <p style="color: #333; line-height: 1.6; font-style: italic; white-space: pre-line;">"${message}"</p>
            </div>

            <div style="margin-top: 30px; text-align: center;">
              <a href="mailto:${email}" style="background-color: #007bff; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">Reply to Lead</a>
            </div>
          </div>

          <div style="background-color: #f1f3f5; padding: 20px; text-align: center; border-top: 1px solid #e1e8ed;">
            <p style="margin: 0; color: #999; font-size: 12px;">This email was automatically generated by your Next.js Website.</p>
          </div>
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"${name}" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER,
      replyTo: email,
      subject: `📩 Contact Details: ${name}`,
      html: htmlTemplate,
    };
    await transporter.sendMail(mailOptions);
    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Nodemailer Error:", error);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}
