import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "./globals.css";
import Header from "./Componets/header";
import Footer from './Componets/Footer/footer'
import SocialMediaBar from "./Componets/SocialMediaBar/SocialMediaBar";
import { Poppins } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose what you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} cz-shortcut-listen="true">
        <SocialMediaBar />
        <Header />
        <div className="bg-light" style={{ marginTop: "75px" }}>
          {children}
        </div>
        <Footer />
        <div id="modal"></div>
      </body>
    </html>
  );
}
